use origin_asset::OriginClient;

#[tokio::main]
async fn main() -> origin_asset::Result<()> {
    let api_key = std::env::var("ORIGIN_API_KEY").expect("set ORIGIN_API_KEY env var");
    let client = OriginClient::new(api_key);

    // --- Asset Gateway: generate an image ---
    let image = client
        .asset()
        .generate_image("a crystal sword glowing with blue fire", None)
        .await?;
    println!(
        "Image generated by {}: {:?}",
        image.provider_id, image.output_url
    );

    // --- AI Search: search the web ---
    let results = client.search().search_fast("Rust async runtime").await?;
    println!(
        "Search returned {} results via {:?}",
        results.results.len(),
        results.providers
    );
    println!("Summary: {}", &results.content[..200.min(results.content.len())]);

    // --- Cognee: search knowledge graph ---
    let knowledge = client.cognee().search("game combat system", None).await?;
    println!("Knowledge: {knowledge}");

    Ok(())
}
